# Generated by Django 5.2.3 on 2025-06-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.IntegerField()),
                ('geography', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('tenure', models.IntegerField()),
                ('balance', models.FloatField()),
                ('num_of_products', models.IntegerField()),
                ('has_cr_card', models.BooleanField()),
                ('is_active_member', models.BooleanField()),
                ('estimated_salary', models.FloatField()),
                ('model_used', models.CharField(max_length=50)),
                ('prediction_result', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
