# Generated by Django 5.2.3 on 2025-07-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churn', '0004_remove_telecomprediction_prediction_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('membership_status', models.CharField(max_length=50)),
                ('avg_transaction_value', models.FloatField()),
                ('purchase_frequency', models.FloatField()),
                ('recency_days', models.IntegerField()),
                ('total_spent', models.FloatField()),
                ('preferred_category', models.CharField(max_length=100)),
                ('discount_usage', models.BooleanField()),
                ('is_loyalty_member', models.BooleanField()),
                ('predicted_churn', models.CharField(default='No', max_length=10)),
                ('churn_probability', models.FloatField(default=0.0)),
                ('model_used', models.CharField(default='retail_random_forest', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
