# Generated by Django 5.2.3 on 2025-07-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churn', '0005_retailprediction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailprediction',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='retailprediction',
            name='age',
        ),
        migrations.RemoveField(
            model_name='retailprediction',
            name='avg_transaction_value',
        ),
        migrations.RemoveField(
            model_name='retailprediction',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='retailprediction',
            name='discount_usage',
        ),
        migrations.RemoveField(
            model_name='retailprediction',
            name='is_loyalty_member',
        ),
        migrations.RemoveField(
            model_name='retailprediction',
            name='location',
        ),
        migrations.RemoveField(
            model_name='retailprediction',
            name='membership_status',
        ),
        migrations.RemoveField(
            model_name='retailprediction',
            name='predicted_churn',
        ),
        migrations.RemoveField(
            model_name='retailprediction',
            name='preferred_category',
        ),
        migrations.RemoveField(
            model_name='retailprediction',
            name='purchase_frequency',
        ),
        migrations.RemoveField(
            model_name='retailprediction',
            name='recency_days',
        ),
        migrations.RemoveField(
            model_name='retailprediction',
            name='total_spent',
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='cashback_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='city_tier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='complain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='coupon_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='day_since_last_order',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='hour_spend_on_app',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='marital_status',
            field=models.CharField(default='Single', max_length=20),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='number_of_address',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='number_of_device_registered',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='order_amount_hike_fromlast_year',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='order_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='prediction_result',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='prefered_order_cat',
            field=models.CharField(default='Others', max_length=50),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='preferred_login_device',
            field=models.CharField(default='Mobile Phone', max_length=50),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='preferred_payment_mode',
            field=models.CharField(default='Cash on Delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='satisfaction_score',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='tenure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='retailprediction',
            name='warehouse_to_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='retailprediction',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='retailprediction',
            name='model_used',
            field=models.CharField(default='retail_model', max_length=100),
        ),
    ]
